require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/klasses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Klass. As you add validations to Klass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Klass.create! valid_attributes
      get klasses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      klass = Klass.create! valid_attributes
      get klass_url(klass)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_klass_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      klass = Klass.create! valid_attributes
      get edit_klass_url(klass)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Klass" do
        expect {
          post klasses_url, params: { klass: valid_attributes }
        }.to change(Klass, :count).by(1)
      end

      it "redirects to the created klass" do
        post klasses_url, params: { klass: valid_attributes }
        expect(response).to redirect_to(klass_url(Klass.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Klass" do
        expect {
          post klasses_url, params: { klass: invalid_attributes }
        }.to change(Klass, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post klasses_url, params: { klass: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested klass" do
        klass = Klass.create! valid_attributes
        patch klass_url(klass), params: { klass: new_attributes }
        klass.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the klass" do
        klass = Klass.create! valid_attributes
        patch klass_url(klass), params: { klass: new_attributes }
        klass.reload
        expect(response).to redirect_to(klass_url(klass))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        klass = Klass.create! valid_attributes
        patch klass_url(klass), params: { klass: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested klass" do
      klass = Klass.create! valid_attributes
      expect {
        delete klass_url(klass)
      }.to change(Klass, :count).by(-1)
    end

    it "redirects to the klasses list" do
      klass = Klass.create! valid_attributes
      delete klass_url(klass)
      expect(response).to redirect_to(klasses_url)
    end
  end
end
